In [29]:
import featuretools as ft
import pandas as pd

In [30]:
# Read the CSV file into a DataFrame
df = pd.read_csv('new_AirQualityUCI.csv')

# Create a new DataFrame "AirQualityMeasurements"
AirQuality = df[['MeasurementID','ReadingID','DateID', 'TimeID']]

# Create a new DataFrame "AirQualityMeasurements"
AirQualityMeasurements = df[['MeasurementID','CO_Concentration', 'NMHC_Concentration', 'Benzene_Concentration', 'NOx_Concentration', 'NO2_Concentration', 'Temperature', 'Relative_Humidity', 'Absolute_Humidity']]

# Create a new DataFrame "SensorReadings"
SensorReadings = df[['ReadingID', 'PT08_S1', 'PT08_S2', 'PT08_S3', 'PT08_S4', 'PT08_S5']]

In [31]:
AirQuality.head()

   MeasurementID  ReadingID  DateID  TimeID
0              1          1       1       1
1              2          2       2       2
2              3          3       3       3
3              4          4       4       4
4              5          5       5       5

In [32]:
AirQualityMeasurements.head()

,MeasurementID,CO_Concentration,NMHC_Concentration,Benzene_Concentration,NOx_Concentration,NO2_Concentration,Temperature,Relative_Humidity,Absolute_Humidity
0,1,2.6,150.0,11.9,166.0,113.0,13.6,48.9,0.7578
1,2,2.0,112.0,9.4,103.0,92.0,13.3,47.7,0.7255
2,3,2.2,88.0,9.0,131.0,114.0,11.9,54.0,0.7502
3,4,2.2,80.0,9.2,172.0,122.0,11.0,60.0,0.7867
4,5,1.6,51.0,6.5,131.0,116.0,11.2,59.6,0.7888

In [33]:
SensorReadings.head()

   ReadingID  PT08_S1  PT08_S2  PT08_S3  PT08_S4  PT08_S5
0          1   1360.0   1046.0   1056.0   1692.0   1268.0
1          2   1292.0    955.0   1174.0   1559.0    972.0
2          3   1402.0    939.0   1140.0   1555.0   1074.0
3          4   1376.0    948.0   1092.0   1584.0   1203.0
4          5   1272.0    836.0   1205.0   1490.0   1110.0

In [34]:
dataframes = {
    "AirQualityMeasurements": (AirQualityMeasurements, "MeasurementID"),
    "SensorReadings": (SensorReadings, "ReadingID"),
    "AirQuality": (AirQuality, "DateID"),
}

In [35]:
relationships = [
    ("SensorReadings", "ReadingID", "AirQuality", "ReadingID"),
    ("AirQualityMeasurements", "MeasurementID","AirQuality","MeasurementID")
]

In [36]:
feature_matrix_SensorReadings, features_defs = ft.dfs(
    dataframes=dataframes,
    relationships=relationships,
    target_dataframe_name="SensorReadings",
)
feature_matrix_SensorReadings

,PT08_S1,PT08_S2,PT08_S3,PT08_S4,PT08_S5,COUNT(AirQuality),MAX(AirQuality.TimeID),MEAN(AirQuality.TimeID),MIN(AirQuality.TimeID),SKEW(AirQuality.TimeID),...,STD(AirQuality.AirQualityMeasurements.Relative_Humidity),STD(AirQuality.AirQualityMeasurements.Temperature),SUM(AirQuality.AirQualityMeasurements.Absolute_Humidity),SUM(AirQuality.AirQualityMeasurements.Benzene_Concentration),SUM(AirQuality.AirQualityMeasurements.CO_Concentration),SUM(AirQuality.AirQualityMeasurements.NMHC_Concentration),SUM(AirQuality.AirQualityMeasurements.NO2_Concentration),SUM(AirQuality.AirQualityMeasurements.NOx_Concentration),SUM(AirQuality.AirQualityMeasurements.Relative_Humidity),SUM(AirQuality.AirQualityMeasurements.Temperature)
ReadingID,,,,,,,,,,,,,,,,,,,,,
1,1360,1046,1056,1692,1268,1,1.0,1.0,1.0,NaN,...,NaN,NaN,0.7578,11.9,2.6,150.0,113.0,166.0,48.9,13.6
2,1292,955,1174,1559,972,1,2.0,2.0,2.0,NaN,...,NaN,NaN,0.7255,9.4,2.0,112.0,92.0,103.0,47.7,13.3
3,1402,939,1140,1555,1074,1,3.0,3.0,3.0,NaN,...,NaN,NaN,0.7502,9.0,2.2,88.0,114.0,131.0,54.0,11.9
4,1376,948,1092,1584,1203,1,4.0,4.0,4.0,NaN,...,NaN,NaN,0.7867,9.2,2.2,80.0,122.0,172.0,60.0,11.0
5,1272,836,1205,1490,1110,1,5.0,5.0,5.0,NaN,...,NaN,NaN,0.7888,6.5,1.6,51.0,116.0,131.0,59.6,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9467,<NA>,<NA>,<NA>,<NA>,<NA>,1,9467.0,9467.0,9467.0,NaN,...,NaN,NaN,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9468,<NA>,<NA>,<NA>,<NA>,<NA>,1,9468.0,9468.0,9468.0,NaN,...,NaN,NaN,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9469,<NA>,<NA>,<NA>,<NA>,<NA>,1,9469.0,9469.0,9469.0,NaN,...,NaN,NaN,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9470,<NA>,<NA>,<NA>,<NA>,<NA>,1,9470.0,9470.0,9470.0,NaN,...,NaN,NaN,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9471,<NA>,<NA>,<NA>,<NA>,<NA>,1,9471.0,9471.0,9471.0,NaN,...,NaN,NaN,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0